@extends('layouts.app')

@section('content')
<div class="container mx-auto px-4 py-8 max-w-4xl">
    <div class="mb-6">
        <a href="{{ route('photos.index') }}" class="text-blue-600 hover:text-blue-700">
            <i class="fas fa-arrow-left mr-2"></i>Kembali
        </a>
    </div>

    <div class="bg-white rounded-lg shadow-lg p-6">
        <h1 class="text-2xl font-bold text-gray-800 mb-6">Upload Foto</h1>

        <form action="{{ route('photos.store') }}" method="POST" enctype="multipart/form-data" id="uploadForm">
            @csrf


            <!-- Default Metadata (Applies to all unless overridden) -->
            <div class="bg-blue-50 p-4 rounded-lg mb-6 border border-blue-100">
                <h3 class="text-blue-800 font-medium mb-3 text-sm uppercase tracking-wide">Pengaturan Default (Untuk Semua Foto)</h3>
                <div class="mb-4">
                    <label class="block text-gray-700 font-medium mb-2">Judul Utama</label>
                    <input type="text" 
                           name="default_title" 
                           id="default_title"
                           class="w-full border border-gray-300 rounded-lg px-4 py-2 focus:ring-2 focus:ring-blue-500"
                           placeholder="Contoh: Kegiatan Dies Natalis 2024">
                    <p class="text-xs text-gray-500 mt-1">Jika judul per foto dikosongkan, judul ini yang akan dipakai.</p>
                </div>
                <div class="mb-2">
                    <label class="block text-gray-700 font-medium mb-2">Deskripsi Umum</label>
                    <textarea 
                           name="default_description" 
                           class="w-full border border-gray-300 rounded-lg px-4 py-2 focus:ring-2 focus:ring-blue-500"
                           placeholder="Deskripsi umum untuk semua foto yang diupload..."></textarea>
                </div>
            </div>

            <!-- File Upload Area -->
            <div class="mb-6">
                <label class="block text-gray-700 font-medium mb-2">Pilih Foto *</label>
                <div class="border-2 border-dashed border-gray-300 rounded-lg p-8 text-center hover:border-blue-500 transition relative" id="drop-area">
                    <input type="file" 
                           name="photos[]" 
                           id="photos" 
                           multiple 
                           accept="image/jpeg,image/jpg,image/png"
                           class="hidden"
                           required>
                    <label for="photos" class="cursor-pointer block w-full h-full">
                        <i class="fas fa-cloud-upload-alt text-5xl text-gray-400 mb-3"></i>
                        <p class="text-gray-600 font-medium mb-1">Klik untuk pilih foto</p>
                        <p class="text-gray-500 text-sm">atau drag & drop foto di sini</p>
                        <p class="text-gray-400 text-xs mt-2">Format: JPG, JPEG, PNG (Max: 10MB per foto)</p>
                    </label>
                </div>
                @error('photos')
                <p class="text-red-500 text-sm mt-1">{{ $message }}</p>
                @enderror
                @error('photos.*')
                <p class="text-red-500 text-sm mt-1">Salah satu file tidak valid (Maks 10MB, Format Gambar).</p>
                @enderror
            </div>

            <!-- Preview Area (Generated by JS) -->
            <div id="preview" class="mb-6 hidden">
                <div class="flex justify-between items-end mb-3">
                    <h3 class="text-gray-700 font-medium">Detail Per Foto</h3>
                    <span class="text-xs text-gray-500 italic">Anda bisa mengubah judul/deskripsi spesifik di bawah ini</span>
                </div>
                <div id="preview-container" class="space-y-4 max-h-[600px] overflow-y-auto pr-2"></div>
            </div>

            <!-- Common Metadata -->
            <div class="grid md:grid-cols-2 gap-6 mb-6 border-t pt-6">
                <div>
                    <label class="block text-gray-700 font-medium mb-2">Fotografer</label>
                    <input type="text" 
                           name="photographer" 
                           class="w-full border border-gray-300 rounded-lg px-4 py-2 focus:ring-2 focus:ring-blue-500"
                           value="{{ old('photographer', auth()->user()->name) }}">
                </div>

                <div>
                    <label class="block text-gray-700 font-medium mb-2">Tanggal Pengambilan</label>
                    <input type="date" 
                           name="taken_date" 
                           class="w-full border border-gray-300 rounded-lg px-4 py-2 focus:ring-2 focus:ring-blue-500"
                           value="{{ old('taken_date', date('Y-m-d')) }}">
                </div>

                <div class="md:col-span-2">
                    <label class="block text-gray-700 font-medium mb-2">Lokasi</label>
                    <input type="text" 
                           name="location" 
                           class="w-full border border-gray-300 rounded-lg px-4 py-2 focus:ring-2 focus:ring-blue-500"
                           placeholder="Lokasi pengambilan foto">
                </div>
            </div>

            <!-- Settings -->
            <div class="mb-6 space-y-3 bg-gray-50 p-4 rounded-lg">
                <label class="flex items-center cursor-pointer">
                    <input type="checkbox" name="is_featured" value="1" class="mr-2 rounded text-blue-600 focus:ring-blue-500">
                    <span class="text-gray-700">Tandai sebagai foto unggulan (Featured)</span>
                </label>
                <label class="flex items-center cursor-pointer">
                    <input type="checkbox" name="is_public" value="1" checked class="mr-2 rounded text-blue-600 focus:ring-blue-500">
                    <span class="text-gray-700">Tampilkan di galeri publik</span>
                </label>
            </div>

            <!-- Actions -->
            <div class="flex justify-end gap-3">
                <a href="{{ route('photos.index') }}" 
                   class="px-6 py-2 border border-gray-300 rounded-lg text-gray-700 hover:bg-gray-50 font-medium">
                    Batal
                </a>
                <button type="submit" 
                        id="submitBtn"
                        class="bg-blue-600 text-white px-6 py-2 rounded-lg hover:bg-blue-700 transition font-medium shadow-md flex items-center">
                    <i class="fas fa-upload mr-2"></i>Upload Foto
                </button>
            </div>
        </form>
    </div>
</div>

@push('scripts')
<script>
// Album selector helper
const albumSelect = document.getElementById('album_select');
const albumInput = document.getElementById('album_input');

if (albumSelect) {
    albumSelect.addEventListener('change', function() {
        if(this.value) {
            albumInput.value = this.value;
        }
    });
}

// File preview logic
const photoInput = document.getElementById('photos');
const previewArea = document.getElementById('preview');
const previewContainer = document.getElementById('preview-container');
const defaultTitleInput = document.getElementById('default_title');

photoInput.addEventListener('change', function(e) {
    const files = Array.from(e.target.files);
    
    if (files.length === 0) {
        previewArea.classList.add('hidden');
        return;
    }

    previewArea.classList.remove('hidden');
    previewContainer.innerHTML = '';
    
    // Ambil nilai default title saat ini (jika ada)
    const currentDefaultTitle = defaultTitleInput.value;

    files.forEach((file, index) => {
        const reader = new FileReader();
        
        reader.onload = function(e) {
            const div = document.createElement('div');
            div.className = 'bg-gray-50 rounded-lg p-4 flex gap-4 border border-gray-200 items-start';
            
            // Bersihkan nama file dari ekstensi untuk saran judul
            const fileNameClean = file.name.replace(/\.[^/.]+$/, "");
            
            div.innerHTML = `
                <div class="flex-shrink-0">
                    <img src="${e.target.result}" class="w-24 h-24 object-cover rounded shadow-sm">
                    <p class="text-xs text-gray-500 mt-2 text-center">${(file.size / 1024 / 1024).toFixed(2)} MB</p>
                </div>
                <div class="flex-1">
                    <div class="mb-3">
                        <label class="block text-xs text-gray-500 mb-1">Judul Foto</label>
                        <input type="text" 
                               name="titles[]" 
                               placeholder="Judul khusus foto ini (kosongkan untuk pakai default)"
                               class="w-full border border-gray-300 rounded px-3 py-2 text-sm focus:ring-1 focus:ring-blue-500 focus:border-blue-500"
                               value=""> 
                    </div>
                    <div>
                        <label class="block text-xs text-gray-500 mb-1">Deskripsi</label>
                        <textarea name="descriptions[]" 
                                  placeholder="Deskripsi khusus foto ini (opsional)"
                                  rows="2"
                                  class="w-full border border-gray-300 rounded px-3 py-2 text-sm focus:ring-1 focus:ring-blue-500 focus:border-blue-500"></textarea>
                    </div>
                </div>
            `;
            previewContainer.appendChild(div);
        };
        
        reader.readAsDataURL(file);
    });
});

// Upload Form Submission handling (Loading State)
document.getElementById('uploadForm').addEventListener('submit', function() {
    const btn = document.getElementById('submitBtn');
    btn.disabled = true;
    btn.innerHTML = '<i class="fas fa-spinner fa-spin mr-2"></i> Mengunggah...';
    btn.classList.add('opacity-75', 'cursor-not-allowed');
});

// Drag & drop Visuals
const dropArea = document.getElementById('drop-area');

['dragenter', 'dragover', 'dragleave', 'drop'].forEach(eventName => {
    dropArea.addEventListener(eventName, preventDefaults, false);
});

function preventDefaults(e) {
    e.preventDefault();
    e.stopPropagation();
}

['dragenter', 'dragover'].forEach(eventName => {
    dropArea.addEventListener(eventName, () => {
        dropArea.classList.add('border-blue-500', 'bg-blue-50');
    });
});

['dragleave', 'drop'].forEach(eventName => {
    dropArea.addEventListener(eventName, () => {
        dropArea.classList.remove('border-blue-500', 'bg-blue-50');
    });
});

dropArea.addEventListener('drop', function(e) {
    const dt = e.dataTransfer;
    const files = dt.files;
    photoInput.files = files;
    photoInput.dispatchEvent(new Event('change'));
});
</script>
@endpush
@endsection